### ISSUE TITLE
Is a release coming?

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/supreme#18]
Hi @erykoff 
We have a DESC python jupyter kernel at DESC and Johann asked about adding supreme to that environment.  I'm happy to do so.  Typically, I'd want to grab a tagged release so I can keep track of what I've added to the env.  Are there plans for a release?  Should I just add `master` for now?  Or wait until a later time?

**Comment by erykoff** [comment]
This week I'm working on proper tests for imsim data, and until those are in I don't think we should include this in the environment.  By the end of the week I'll tag a version that I think can be included.

**Comment by erykoff** [comment]
@heather999 I have now tagged `v0.1` of `supreme`, and this is tested and though rough (especially with validation of the config yamls, which is non-existent), it is usable enough.
